travis:
  secure:
    BINSTAR_TOKEN: sue8b/l7tjXO+7q9unbE0layU/MGzhdhokeAZZoGxlChIfkjkqUHXAHfy0FT8Ikk0uszMtQim6QH2BzkEi/q+KhEu4AvP+646+Tg15d/0il3P/xN9SAX++4kiShtnV+A+w5I8TcuhHGmmtEJxRutbqsE+Rr7oxmCCxyYujEAzHN+vHqvM4JkBApJio9SPxzI432xEiWhvP6m7VRZ74fyJb4E8udWFRbJSL698wpAfckeHJFiXVhNZ14Frtoz/Ws1a1250uKHBAF5ne075EA/JnzVjlejf8A8mfNrLrShBvnd4XVtmVRazAAiZRH83P5KDPWbMZ1FuR57xKOVspsYkZWVhfMvB7s9Rjy7br/L8Gm5/js761kr0gNK0Tra63YmbMcwQhyNM8zDpbSHURwvY1OXr1iQ5P1BI4MNxZcqqXmmW9vQQFWQ5poVxodRVGKg13DhFdpyk12mDaPGOGrJjjkcwDL/vOjYURph3B8WCozf/Gy0Hca3vUWQT9GOVgX4eZhQ5LfWreHZU4CkvEo+5AH2/3knu23seXw2arzaj3QaIbljsBwM+9roFB6wVk+2kaK7hcHmw8BrF/jAggcAARtixI4vLoKF4yPwzydLPkZDLQJY277s5bZve2BBVuENQVFUGXK6bcN5leeOtYcrgNuaf/8OuJG8m1655oMRWXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
